site_name: Sathvick Srinath
site_author: Sathvick Bindinganavale Srinath
site_description: I'm Sathvick, a Mechatronics graduate student from THWS, Germany with a focus and interest in software engineering, automation and data science.
theme:
  name: material
  logo: img/graduate_icon.ico
markdown_extensions:
  - attr_list

nav:
  - Home: index.md
  - Projects:
    - Artist Insight Hub : projects/artist-insight-hub.md
    - CinesphereX : projects/cinespherex.md
    - Resistor Reel Cutter Machine : projects/resistor-reel-cutter-machine.md
    - AI Chatbot : ai_chatbot.md
  - Certifications: certifications/certifications.md